import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";

const production = process.argv[2] === "production";
const pdfjsLicense = readFileSync(
  new URL("node_modules/pdfjs-dist/LICENSE", import.meta.url),
  "utf8"
).trim();
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
Source code is available in the plugin's GitHub repository.
Includes Mozilla PDF.js, licensed under Apache-2.0.
See THIRD_PARTY_LICENSES.txt in the source repository and release assets.

${pdfjsLicense}
*/`;

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
